---
filters:
  - default.js
  - md2html.js
  - percent.js
  - tabLabel.js
  - as_float.js
  - add.js
  - title.js
  - as_array.js
  - sortItemsByArray.js
  - breakpoint.js
  - breakpoints.js
  - position_x.js
  - width_x.js
  - length.js
  - layer_is_visible.js
  - common/append.js
  - common/default_if_undefined.js
  - common/default_if_undefined_or_blank.js
  - common/extract.js
  - common/extractTest.js
  - common/inArray.js
  - common/not.js
  - common/prepend.js
  - common/parseTrue.js
  - common/ternary.js
  - common/ternary_defined.js
  - common/yaml.js
  - array/arrayToObject.js
  - array/join.js
  - array/first.js
  - array/last.js
  - array/choose.js
  - format/css.js
  - format/formatBreakPoint.js
  - format/formatFloat.js
  - format/formatInteger.js
  - format/formatArray.js
  - format/formatMonth.js
  - math/eq.js
  - math/lte.js
  - math/gte.js
  - math/gt.js
  - string/replace.js
  - string/split.js
  - string/stringToObject.js
  - url/url_shapefile.js
  - url/url_geojson.js
  - url/url_kml.js
  - url/url_describefeaturetype.js
